'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Bell, Eye, EyeOff, KeyRound, Check, CloudSun, Edit3, Mail, Plus, Search, UserCog, UserCircle, Users, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import '../app/profile-settings/profile-settings.css';
import '../app/profile/profile.css';

const MODULES=['Overview','Farm management','Supply management','Trading','Training','Traceability','Lots & transactions'];
type User = { id:string; name:string; email:string; role:string; status:'Active'|'Invited'|'Suspended'; initials:string; password:string; modules:string[] };
// Columns persisted to Supabase (public.app_users). Passwords are hashed server-side.
const DB_COLS='id,name,email,role,status,initials,modules';
const seed:User[]=[
  {id:'1',name:'Kenneth Owori',email:'kenneth@trustandtrade.org',role:'Administrator',status:'Active',initials:'KO',password:'',modules:MODULES},
  {id:'2',name:'Sarah Nakato',email:'sarah.nakato@trustandtrade.org',role:'Farm Manager',status:'Active',initials:'SN',password:'',modules:['Overview','Farm management','Supply management']},
  {id:'3',name:'David Okello',email:'david.okello@trustandtrade.org',role:'Field Officer',status:'Active',initials:'DO',password:'',modules:['Overview','Farm management','Traceability']},
  {id:'4',name:'Mercy Achieng',email:'mercy.achieng@trustandtrade.org',role:'Data Analyst',status:'Invited',initials:'MA',password:'',modules:['Overview','Trading','Lots & transactions']},
  {id:'5',name:'Ivan Mugisha',email:'ivan.mugisha@trustandtrade.org',role:'Viewer',status:'Suspended',initials:'IM',password:'',modules:['Overview']},
];
const blank={name:'',email:'',role:'Viewer',status:'Active' as 'Active'|'Invited'|'Suspended',password:'',confirm:'',modules:['Overview'] as string[]};
const genPassword=()=>{const c='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%';const a=new Uint32Array(12);crypto.getRandomValues(a);return Array.from(a,n=>c[n%c.length]).join('')};

export default function UserManagement({embedded=false,canManage=true}:{embedded?:boolean;canManage?:boolean}){
  const [users,setUsers]=useState(seed); const [query,setQuery]=useState(''); const [editing,setEditing]=useState<User|null>(null); const [open,setOpen]=useState(false); const [form,setForm]=useState(blank); const [saved,setSaved]=useState(false); const [showPw,setShowPw]=useState(false); const [error,setError]=useState('');
  const filtered=useMemo(()=>users.filter(u=>(u.name+u.email+u.role).toLowerCase().includes(query.toLowerCase())),[users,query]);
  useEffect(()=>{if(!supabase)return;let alive=true;(async()=>{const{data,error}=await supabase!.from('app_users').select(DB_COLS).order('created_at',{ascending:true});if(alive&&!error&&data&&data.length)setUsers(data.map(d=>({...(d as Omit<User,'password'>),password:''})))})();return()=>{alive=false}},[]);
  function startCreate(){setEditing(null);setForm(blank);setError('');setOpen(true)}
  function startEdit(u:User){setEditing(u);setForm({name:u.name,email:u.email,role:u.role,status:u.status,password:'',confirm:'',modules:u.modules});setError('');setOpen(true)}
  function toggleModule(m:string){setForm(f=>({...f,modules:f.modules.includes(m)?f.modules.filter(x=>x!==m):[...f.modules,m]}))}
  async function submit(e:FormEvent){e.preventDefault();if(!editing&&!form.password)return setError('Set a password for the new user.');if(form.password&&form.password.length<8)return setError('Password must be at least 8 characters.');if(form.password!==form.confirm)return setError('Passwords do not match.');if(form.modules.length===0)return setError('Assign at least one module.');if(users.some(u=>u.email.toLowerCase()===form.email.toLowerCase()&&u.id!==editing?.id))return setError('A user with this email already exists.');const initials=form.name.split(' ').map(n=>n[0]).join('').slice(0,2).toUpperCase();const payload={name:form.name,email:form.email,role:form.role,status:form.status,initials,modules:form.modules,password:form.password||undefined};try{const res=await fetch('/api/users',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{...payload,id:editing.id}:payload)});const data=await res.json();if(!data.ok)return setError(data.reason||'Could not save the user.');const savedUser=data.user as User;if(editing)setUsers(v=>v.map(u=>u.id===editing.id?{...u,...savedUser,password:''}:u));else setUsers(v=>[{...savedUser,password:''},...v])}catch{return setError('Could not reach the server. Try again.')}setOpen(false);setSaved(true);setTimeout(()=>setSaved(false),1800)}
  const body=<><div className="profile-page"><div className="profile-heading"><div><span>ORGANIZATION SETTINGS</span><h1>User management</h1><p>Manage team access, roles and account status.</p></div>{canManage?<button className="add-user" onClick={startCreate}><Plus/>Add user</button>:<span className="viewer-note">View only · admins manage users</span>}</div>
        {saved&&<div className="toast"><Check/>Changes saved successfully</div>}
        <section className="identity-card"><div className="identity-avatar">KO</div><div><h2>Kenneth Owori</h2><p>kenneth@trustandtrade.org</p><span>Administrator</span></div>{canManage&&<button onClick={()=>startEdit(users[0])}><Edit3/>Edit profile</button>}</section>
        <section className="user-section"><div className="section-top"><div><h2>Organization users</h2><p>{users.length} people have access to Trust&amp;Trade pilot</p></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users..."/></label></div>
          <div className="user-table"><table><thead><tr><th>User</th><th>Role</th><th>Modules</th><th>Status</th><th>Last active</th><th></th></tr></thead><tbody>{filtered.map((u,i)=><tr key={u.id}><td><div className="user-cell"><i>{u.initials}</i><div><b>{u.name}</b><span>{u.email}</span></div></div></td><td><span className="role">{u.role}</span></td><td><span className="module-count" title={u.modules.join(', ')}>{u.modules.length===MODULES.length?'All modules':`${u.modules.length} of ${MODULES.length}`}</span></td><td><span className={'user-status '+u.status.toLowerCase()}><i/>{u.status}</span></td><td>{i===0?'Just now':i===1?'12 min ago':i===2?'Yesterday':'—'}</td><td>{canManage&&<button onClick={()=>startEdit(u)} aria-label={`Edit ${u.name}`}><Edit3/></button>}</td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty">No users match your search.</div>}</div>
        </section>
      </div>
    {open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form className="user-modal" onSubmit={submit}><div className="modal-top"><div><span>{editing?'EDIT USER':'NEW USER'}</span><h2>{editing?'Update team member':'Add a team member'}</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Grace Namusoke"/></label><label>Email address<div className="email-input"><Mail/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="name@organization.org"/></div></label><div className="form-row"><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Administrator</option><option>Farm Manager</option><option>Field Officer</option><option>Data Analyst</option><option>Viewer</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as any})}><option>Active</option><option>Invited</option><option>Suspended</option></select></label></div><div className="form-row"><label>{editing?'New password':'Password'}<div className="pw-input"><input type={showPw?'text':'password'} autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder={editing?'Leave blank to keep current':'At least 8 characters'}/><button type="button" onClick={()=>setShowPw(v=>!v)} aria-label={showPw?'Hide password':'Show password'}>{showPw?<EyeOff/>:<Eye/>}</button></div></label><label>Confirm password<input type={showPw?'text':'password'} autoComplete="new-password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></label></div><button type="button" className="gen-pw" onClick={()=>{const p=genPassword();setForm({...form,password:p,confirm:p});setShowPw(true)}}><KeyRound/>Generate strong password</button>
      <fieldset className="module-picker"><legend>Module access <button type="button" onClick={()=>setForm({...form,modules:form.modules.length===MODULES.length?[]:MODULES})}>{form.modules.length===MODULES.length?'Clear all':'Select all'}</button></legend>{MODULES.map(m=><label key={m} className={form.modules.includes(m)?'on':''}><input type="checkbox" checked={form.modules.includes(m)} onChange={()=>toggleModule(m)}/>{m}</label>)}</fieldset>
      {error&&<p className="form-error">{error}</p>}
      <div className="modal-actions"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="save" type="submit">{editing?'Save changes':'Create user'}</button></div></form></div>}
  </>;
  if(embedded)return body;
  return <main className="profile-app">
    <aside className="profile-side"><a className="profile-brand" href="/"><img src="/farmerlink.svg" alt="FarmerLink"/></a><a className="back" href="/"><ArrowLeft/>Back to dashboard</a><p>SETTINGS</p><nav><button className="selected"><Users/>User management</button><a href="/profile"><button><UserCog/>User profile</button></a></nav><footer><i>KO</i><div><b>Kenneth Owori</b><small>Administrator</small></div></footer></aside>
    <section className="profile-content"><header><label><Search/><input placeholder="Search settings..."/></label><div className="header-cluster"><button className="weather" aria-label="Current weather"><CloudSun/><span>24°C</span></button><button className="notice" aria-label="Notifications"><Bell/><i/></button><button className="profile-chip" aria-label="Open account menu">KO</button></div></header>
      {body}</section></main>
}
